# version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sinta
    ports:
      - "5433:5432" # Mapeia a porta 5433 do host para a 5432 do container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sinta
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
